-- MySQL Script generated by MySQL Workbench
-- Sex 04 Nov 2016 16:30:09 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema frota
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frota
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frota` DEFAULT CHARACTER SET latin1 ;
USE `frota` ;

-- -----------------------------------------------------
-- Table `frota`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`cargos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`cidade` (
  `cidade` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`funcionarios` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `cnh` VARCHAR(45) NULL DEFAULT NULL,
  `aniversario` DATE NULL DEFAULT NULL,
  `cidade_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionarios_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_funcionarios_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `frota`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`cargos_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`cargos_funcionarios` (
  `cargos_id` INT(11) NOT NULL,
  `funcionarios_id` INT(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_table1_cargos_idx` (`cargos_id` ASC),
  INDEX `fk_user_cargo_users1_idx` (`funcionarios_id` ASC),
  CONSTRAINT `fk_table1_cargos`
    FOREIGN KEY (`cargos_id`)
    REFERENCES `frota`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_cargo_users1`
    FOREIGN KEY (`funcionarios_id`)
    REFERENCES `frota`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`carteira_motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`carteira_motorista` (
  `categoria` VARCHAR(1) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`cnh_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`cnh_funcionario` (
  `tipo_cnh_id` INT(11) NOT NULL,
  `funcionarios_id` INT(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_cnh_funcionario_cateira_motorista1_idx` (`tipo_cnh_id` ASC),
  INDEX `fk_cnh_funcionario_funcionarios1_idx` (`funcionarios_id` ASC),
  CONSTRAINT `fk_cnh_funcionario_cateira_motorista1`
    FOREIGN KEY (`tipo_cnh_id`)
    REFERENCES `frota`.`carteira_motorista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnh_funcionario_funcionarios1`
    FOREIGN KEY (`funcionarios_id`)
    REFERENCES `frota`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`manutencoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`manutencoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manutencao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`veiculos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`manutencoes_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`manutencoes_veiculos` (
  `veiculos_id` INT(11) NOT NULL,
  `manutencoes_id` INT(11) NOT NULL,
  `funcionarios_id` INT(10) NOT NULL,
  INDEX `fk_manutencoes_veiculos1_idx` (`veiculos_id` ASC),
  INDEX `fk_manutencoes_veiculos_manutencoes1_idx` (`manutencoes_id` ASC),
  INDEX `fk_manutencoes_veiculos_funcionarios1_idx` (`funcionarios_id` ASC),
  CONSTRAINT `fk_manutencoes_veiculos1`
    FOREIGN KEY (`veiculos_id`)
    REFERENCES `frota`.`veiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manutencoes_veiculos_funcionarios1`
    FOREIGN KEY (`funcionarios_id`)
    REFERENCES `frota`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manutencoes_veiculos_manutencoes1`
    FOREIGN KEY (`manutencoes_id`)
    REFERENCES `frota`.`manutencoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `frota`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`nota` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_nota` VARCHAR(45) NULL DEFAULT NULL,
  `icms` TINYINT(4) NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `data_emissao` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`rota` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `destino` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`notas_rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`notas_rotas` (
  `nota_id` INT(11) NOT NULL,
  `rota_id` INT(11) NOT NULL,
  INDEX `fk_notas_rotas_nota1_idx` (`nota_id` ASC),
  INDEX `fk_notas_rotas_rota1_idx` (`rota_id` ASC),
  CONSTRAINT `fk_notas_rotas_nota1`
    FOREIGN KEY (`nota_id`)
    REFERENCES `frota`.`nota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_rotas_rota1`
    FOREIGN KEY (`rota_id`)
    REFERENCES `frota`.`rota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`rotas_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`rotas_funcionarios` (
  `rota_id` INT(11) NOT NULL,
  `veiculos_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `horario_saida` TIMESTAMP NULL DEFAULT NULL,
  `horario_chegada` TIMESTAMP NULL DEFAULT NULL,
  `auxiliar_id` INT(10) NOT NULL,
  `motorista_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rotas_funcionarios_rota1_idx` (`rota_id` ASC),
  INDEX `fk_rotas_funcionarios_veiculos1_idx` (`veiculos_id` ASC),
  INDEX `fk_rotas_funcionarios_funcionarios1_idx` (`auxiliar_id` ASC),
  INDEX `fk_rotas_funcionarios_funcionarios2_idx` (`motorista_id` ASC),
  CONSTRAINT `fk_rotas_funcionarios_funcionarios1`
    FOREIGN KEY (`auxiliar_id`)
    REFERENCES `frota`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_funcionarios_funcionarios2`
    FOREIGN KEY (`motorista_id`)
    REFERENCES `frota`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_funcionarios_rota1`
    FOREIGN KEY (`rota_id`)
    REFERENCES `frota`.`rota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_funcionarios_veiculos1`
    FOREIGN KEY (`veiculos_id`)
    REFERENCES `frota`.`veiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`ocorrencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rotas_funcionarios_id` INT(11) NOT NULL,
  `ocorrencia` VARCHAR(1024) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ocorrencia_rotas_funcionarios1_idx` (`rotas_funcionarios_id` ASC),
  CONSTRAINT `fk_ocorrencia_rotas_funcionarios1`
    FOREIGN KEY (`rotas_funcionarios_id`)
    REFERENCES `frota`.`rotas_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frota`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frota`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
